name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"

jobs:
  hacs:
    name: "HACS Action"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: hacs/action@main
        with:
          category: integration
