name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: "Prepare Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: "Set version in manifest"
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version#v}"
          jq --arg v "$version" '.version = $v' \
            custom_components/smart_garage/manifest.json > tmp.json
          mv tmp.json custom_components/smart_garage/manifest.json

      - name: "Create release ZIP"
        run: |
          cd custom_components/smart_garage
          zip -r ../../smart_garage.zip .

      - name: "Upload release asset"
        uses: softprops/action-gh-release@v3
        with:
          files: smart_garage.zip
